import type { EnglishTopic } from '../types';

export const placeholderTopics: EnglishTopic[] = [
  {
    slug: 'plans-invitations',
    title: 'Hẹn hò & lời mời',
    englishTitle: 'Plans & invitations',
    summary: 'Đề xuất kế hoạch, mời, nhận lời, từ chối lịch sự, đổi lịch.',
    level: 'B1+',
    variant: 'daily-life',
    lessons: [],
    placeholder: true,
    plannedLessonCount: 6,
  },
  {
    slug: 'apologies-complaints',
    title: 'Xin lỗi & phàn nàn',
    englishTitle: 'Apologies & complaints',
    summary: 'Xin lỗi nhẹ và xin lỗi thật, phàn nàn lịch sự, leo thang đúng mức, giải quyết mâu thuẫn.',
    level: 'B1+',
    variant: 'daily-life',
    lessons: [],
    placeholder: true,
    plannedLessonCount: 6,
  },
  {
    slug: 'office-small-talk',
    title: 'Trò chuyện ở văn phòng',
    englishTitle: 'Office small talk',
    summary: 'Chào buổi sáng, cuối tuần, mời ăn trưa, "office chat" mà không vượt giới hạn.',
    level: 'B1+',
    variant: 'work',
    lessons: [],
    placeholder: true,
    plannedLessonCount: 6,
  },
  {
    slug: 'meetings',
    title: 'Họp',
    englishTitle: 'Meetings',
    summary: 'Mở đầu, cập nhật/đề xuất, đồng ý/không đồng ý lịch sự, ngắt lời, chốt action items.',
    level: 'B1+',
    variant: 'work',
    lessons: [],
    placeholder: true,
    plannedLessonCount: 6,
  },
  {
    slug: 'job-interview',
    title: 'Phỏng vấn xin việc',
    englishTitle: 'Job interview',
    summary: 'Tự giới thiệu, kinh nghiệm, điểm yếu, câu hỏi cho nhà tuyển dụng, lương & bước tiếp theo.',
    level: 'B2+',
    variant: 'work',
    lessons: [],
    placeholder: true,
    plannedLessonCount: 6,
  },
  {
    slug: 'presentations',
    title: 'Thuyết trình',
    englishTitle: 'Presentations',
    summary: 'Mở bài, dẫn dắt, trình bày dữ liệu, xử lý Q&A, chốt với call-to-action.',
    level: 'B2+',
    variant: 'work',
    lessons: [],
    placeholder: true,
    plannedLessonCount: 6,
  },
];
