import type { EnglishTopic } from '../types';

export const placeholderTopics: EnglishTopic[] = [
  {
    slug: 'greetings-introductions',
    title: 'Chào hỏi & giới thiệu',
    englishTitle: 'Greetings & introductions',
    summary: 'Mở đầu cuộc trò chuyện, giới thiệu bản thân và người khác trong các bối cảnh khác nhau.',
    level: 'B1+',
    variant: 'daily-life',
    lessons: [],
    placeholder: true,
    plannedLessonCount: 5,
  },
  {
    slug: 'small-talk',
    title: 'Trò chuyện xã giao',
    englishTitle: 'Small talk',
    summary: 'Bắt đầu, duy trì và kết thúc cuộc trò chuyện ngắn một cách tự nhiên.',
    level: 'B1+',
    variant: 'daily-life',
    lessons: [],
    placeholder: true,
    plannedLessonCount: 6,
  },
  {
    slug: 'shopping-money',
    title: 'Mua sắm & tiền bạc',
    englishTitle: 'Shopping & money',
    summary: 'Hỏi giá, thử đồ, mặc cả nhẹ nhàng, đổi trả và xử lý phàn nàn.',
    level: 'B1+',
    variant: 'daily-life',
    lessons: [],
    placeholder: true,
    plannedLessonCount: 6,
  },
  {
    slug: 'directions-getting-around',
    title: 'Hỏi đường & di chuyển',
    englishTitle: 'Directions & getting around',
    summary: 'Hỏi đường, hiểu chỉ dẫn, dùng phương tiện công cộng, taxi & ridesharing.',
    level: 'B1+',
    variant: 'daily-life',
    lessons: [],
    placeholder: true,
    plannedLessonCount: 6,
  },
  {
    slug: 'phone-video-calls',
    title: 'Gọi điện & gọi video',
    englishTitle: 'Phone & video calls',
    summary: 'Mở/kết thúc cuộc gọi, để lại tin nhắn, xử lý kết nối kém, video call etiquette.',
    level: 'B1+',
    variant: 'daily-life',
    lessons: [],
    placeholder: true,
    plannedLessonCount: 6,
  },
  {
    slug: 'travel-airport',
    title: 'Du lịch & sân bay',
    englishTitle: 'Travel & airport',
    summary: 'Check-in, an ninh, lên máy bay, hải quan, hành lý thất lạc và delay.',
    level: 'B1+',
    variant: 'daily-life',
    lessons: [],
    placeholder: true,
    plannedLessonCount: 6,
  },
  {
    slug: 'hotel',
    title: 'Khách sạn & nơi ở',
    englishTitle: 'Hotel & accommodation',
    summary: 'Đặt phòng, check-in, hỏi tiện nghi, xử lý vấn đề trong phòng và check-out.',
    level: 'B1+',
    variant: 'daily-life',
    lessons: [],
    placeholder: true,
    plannedLessonCount: 6,
  },
  {
    slug: 'doctor-health',
    title: 'Khám bệnh & sức khoẻ',
    englishTitle: 'Doctor & health',
    summary: 'Đặt lịch, mô tả triệu chứng, hiểu chẩn đoán, hiệu thuốc và tình huống khẩn cấp.',
    level: 'B1+',
    variant: 'daily-life',
    lessons: [],
    placeholder: true,
    plannedLessonCount: 6,
  },
  {
    slug: 'plans-invitations',
    title: 'Hẹn hò & lời mời',
    englishTitle: 'Plans & invitations',
    summary: 'Đề xuất kế hoạch, mời, nhận lời, từ chối lịch sự, đổi lịch.',
    level: 'B1+',
    variant: 'daily-life',
    lessons: [],
    placeholder: true,
    plannedLessonCount: 6,
  },
  {
    slug: 'apologies-complaints',
    title: 'Xin lỗi & phàn nàn',
    englishTitle: 'Apologies & complaints',
    summary: 'Xin lỗi nhẹ và xin lỗi thật, phàn nàn lịch sự, leo thang đúng mức, giải quyết mâu thuẫn.',
    level: 'B1+',
    variant: 'daily-life',
    lessons: [],
    placeholder: true,
    plannedLessonCount: 6,
  },
  {
    slug: 'office-small-talk',
    title: 'Trò chuyện ở văn phòng',
    englishTitle: 'Office small talk',
    summary: 'Chào buổi sáng, cuối tuần, mời ăn trưa, "office chat" mà không vượt giới hạn.',
    level: 'B1+',
    variant: 'work',
    lessons: [],
    placeholder: true,
    plannedLessonCount: 6,
  },
  {
    slug: 'meetings',
    title: 'Họp',
    englishTitle: 'Meetings',
    summary: 'Mở đầu, cập nhật/đề xuất, đồng ý/không đồng ý lịch sự, ngắt lời, chốt action items.',
    level: 'B1+',
    variant: 'work',
    lessons: [],
    placeholder: true,
    plannedLessonCount: 6,
  },
  {
    slug: 'job-interview',
    title: 'Phỏng vấn xin việc',
    englishTitle: 'Job interview',
    summary: 'Tự giới thiệu, kinh nghiệm, điểm yếu, câu hỏi cho nhà tuyển dụng, lương & bước tiếp theo.',
    level: 'B2+',
    variant: 'work',
    lessons: [],
    placeholder: true,
    plannedLessonCount: 6,
  },
  {
    slug: 'presentations',
    title: 'Thuyết trình',
    englishTitle: 'Presentations',
    summary: 'Mở bài, dẫn dắt, trình bày dữ liệu, xử lý Q&A, chốt với call-to-action.',
    level: 'B2+',
    variant: 'work',
    lessons: [],
    placeholder: true,
    plannedLessonCount: 6,
  },
];
